# Generated by Django 4.1.7 on 2023-03-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_issue_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='Status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('In progress', 'In progress'), ('Ready for test', 'Ready for test'), ('Closed', 'Closed'), ('Needs info', 'Needs info')], max_length=50, null=True),
        ),
    ]
